import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* Pages are statically generated by default (SSG).
     sitemap.ts and robots.ts generate at build time. */
};

export default nextConfig;
